### ISSUE TITLE
Instructions on GPU usage

### ISSUE THREAD

**Issue by kylebgorman** [erip/feiertag#3]
`/home/kbg/.anaconda/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: GPU available but not used. Set the --gpus flag when calling the script.` 

But `--gpus=0` didn't work (flag parsing error).

Probably best to document and then suppress that warning.

**Comment by kylebgorman** [comment]
`+train.gpu=0` Is what worked. I guess I have to override some default.

**Comment by erip** [comment]
Was that a typo? I'd expect it to be `+trainer.gpus`.

**Comment by kylebgorman** [comment]
No actually. It did activate the GPU!

**Comment by erip** [comment]
That's very ... interesting. 😄 I might need to add some strictness to the parsing logic as the overriding behavior in hydra should correspond to existing config hierarchies; i.e., `+train.gpus=blah` should add a `gpus: blah` to the global namespace [here](https://github.com/erip/feiertag/blob/master/feiertag/config/train.yaml), whereas `+trainer.gpus=blah` would `gpus: blah` to the trainer namespace [here](https://github.com/erip/feiertag/blob/master/feiertag/config/train.yaml#L4) (which would then be [fed to the PL trainer](https://github.com/erip/feiertag/blob/master/feiertag/cli/train.py#L86)).
